CHANGELOG.md
src/Expect.elm
src/Test/Runner.elm
tests/README.md
tests/src/Tests.elm

As asked on Slack, here are fixes for issues tagged major-release-blocker in the main repo.
There is also mention in 191 (no link for stealth) of removing `Fuzz.conditional`. This is a pretty clunky filtering system that I don't think we should encourage. Anyone feel strongly in favor of keeping it?

Fix major release blockers

---

elm.json
src/Lazy.elm
src/Lazy/List.elm
src/Shrink.elm

cc @eeue56 - turns out there was some nontrivial 0.19 stuff to take care of here (e.g. custom infix operators, tuples over size 3) but that's all taken care of now, and can be backported whenever!

Inline and 0.19ify some eeue56/ deps

---

src/Fuzz.elm

Explain that instead of fuzzing over booleans, you should write two unit
tests. Move the documentation for the function lower in the docs.

Discourage use of `fuzz boolean`.

---

src/Fuzz.elm

Adds back ticks and indents the example to ensure correct rendering.
Hopefully, this will make the doc a bit easier to read 😄

Fix formatting of doc comment for Fuzz.andThen

---

README.md

* use https
* elm-explorations/elm-test -> elm-explorations/test
* link describe to `#describe` instead of `#test`

Fix links to package.elm-lang.org

---

src/Test/Fuzz.elm

This separates concerns into different functions, provides some better names, and deletes out-of-date comments, without changing the signature of the exposed function.
Hopefully this makes the algorithm much less "magic" and "Max's domain knowledge". This PR is a good opportunity for some other folks to become familiar with this code.

Refactor the running of fuzz tests

---

src/Fuzz.elm
src/Simplify.elm
src/Simplify/Internal.elm
tests/src/Helpers.elm
tests/src/SimplifyTests.elm
tests/src/Tests.elm

Do not expose lazy lists at all to the user. Do various other cleanup and polish tasks.
TODO:
- ~~Figure out why we have two exposed ways of running simplification, in `Test.Runner` and in `Simplify`. Likely remove one.~~
- The former runs fuzzers, the latter runs simplifiers. Worthy of further discussion so punting from this PR.
Tagging as major release blocker because there are lots of breaking changes. Ideally we would keep breaking changes off master until we're ready to release but that ship has already sailed.

Improve simplifiers

---

src/Simplify.elm

These functions operate on LazyList, which we are hiding (so this
finishes the work mostly done in #79). Grepping for "lazy" in the
generated docs JSON finds no matches now, so I think there are not any
more that I've missed.
It's impossible to implement these functions (sensibly) if they were to
accept simplifiers instead of lazy lists. A simplifier is a function,
and a value of the type of the argument isn't available.
By deleting the relevant documentation, this closes #65.
Tagging major release blocker for obvious reasons.

Remove Simplify.map and Simplify.andMap

---

src/Fuzz.elm
src/Simplify.elm
src/Test.elm
tests/src/FloatWithinTests.elm
tests/src/FuzzerTests.elm
tests/src/Runner/String.elm

See #48.
I have a slight preference for going with `triplet` over `triple`. This PR uses `triple` although it would be easy for me to change that if folk are keen.

 Rename tuple and tuple3 functions to pair and triple. 

---

tests/src/Runner/String/Format.elm
tests/src/Tests.elm

This adds a unicode-escaped copy of any failing string that contains non-standard ascii characters. 
I'm not completely happy with the formatting, so if you have suggestions, please do tell. Otherwise, I think it's still much better than what we currently have. I'm comparing the escaped strings, not character by character, which is why we're getting diffs that cover part of an escape sequence. 
Solves https://github.com/elm-community/elm-test/issues/225 and #38.
```
↓ Expectations
↓ Expect.equal on unicode strings should show pretty output
✗ ascii
▼        ▼▼       ▼▼  
"\u{1f63b}\u{1f640}\u{1f47b}" (same string but with unicode characters escaped)
▼   
"😻🙀👻"
|> Expect.equal
"🙀👻😻🙈"
▲▲ 
"\u{1f640}\u{1f47b}\u{1f63b}\u{1f648}" (same string but with unicode characters escaped)
▲▲▲▲▲▲▲▲▲▲ …
```

Unicode string test failure output

---

CHANGELOG.md
src/Elm/Kernel/HtmlAsJson.js
tests/src/Test/Html/QueryTests.elm
tests/src/Tests.elm

Fixes https://github.com/elm-explorations/test/issues/78
The issues was actually that evaluated lazy nodes were never recursed into (it turned out to have nothing to do with Html.Keyed)
To fix the Travis-CI build, this also removes the node 4 and node 6 (and adds node 12) CI configs (node 6 was end-of-lifed in April 2019: https://github.com/nodejs/Release#release-schedule).

Fix handling of nested Html.lazy

---

src/Fuzz.elm
src/Fuzz/Internal.elm
tests/src/FuzzerTests.elm

Copy of https://github.com/elm-community/elm-test/pull/204. This PR was originally made for elm 0.18 back in August 2017. We delayed merging it since there was a bug with `String.reverse` where it didn't handle emojis or composite characters correctly. The bug has since been both fixed and published, so all 0.19 elm/core versions now reverse the strings we use in this fuzzer properly. There are still issues with the string reversal algorithm used in elm, but this new fuzzer doesn't generate strings that hit those cases.

Make Fuzz.string generate unicode strings.

---

src/Test.elm

The most common convention in mathematics is that `0` has no sign. The numbers greater than or equal to `0` are generally described with the term "non-negative".

Correct math mistake

---

src/Expect.elm

Hello, 
it seems like the description of `ok` was a direct copy of the description of `err`, so I swapped the words and updated the result.
Also, the `String.toInt` in elm 0.19 returns a `Maybe` (see [docs](https://package.elm-lang.org/packages/elm/core/1.0.0/Result#fromMaybe)), so I added a `Result.fromMaybe` to the examples.
If I should split it into two commits, please say so.

Update `Expect.ok` and `Expect.err` documentation

---

package.json
tests/elm.json
tests/make.sh
tests/test.sh

Upgrading requires a hack to work around compiler error when importing non-local kernel models.
I am not sure it is worth it.

update compiler to 0.19.1

---

src/Test.elm
src/Test/Fuzz.elm
src/Test/Internal.elm
src/Test/Runner.elm

**Explanation for why node-test-runner needs this:** https://github.com/rtfeldman/node-test-runner/pull/442#issuecomment-713526271
(Original discussion leading to this PR: https://github.com/rtfeldman/node-test-runner/pull/442#discussion_r495579878)

Prefix internal Test type variants so node-test-runner can find them

---

README.md

It took me a little bit to find the actual cli implementation, and I figure linking to it in the readme may be helpful to other people. It may be prudent to more explicitly call out the fact that it lives in a separate project, but I figured I'd go with the least invasive change.

Add link to node-test-runner in Readme.md

---

src/Test.elm
tests/src/Runner/String/Format.elm

Just ran across this issue looking at the docs at: https://package.elm-lang.org/packages/elm-explorations/test/latest/Test#fuzz
When I clicked the `Fuzzer` link, it took me to `elm-community/test` which isn't maintained (or compatible with 0.19).
Seraching through the codebase, I looked at every instance of `elm-community`, and most are links to the archived repo (and would break if we tried to link them to this repo now).
I did find another one, where it says to create an issue in the archived repo, which is not possible. Now it says to create an issue in this repo.

Fix links, from elm-community to elm-explorations

---

src/Fuzz.elm

It uses `Random.bool`, however [Random of elm/random 1.0.0 ](https://package.elm-lang.org/packages/elm/random/1.0.0/Random) doesn't contain `bool`.
See also: https://github.com/elm-explorations/test/issues/164

Fix the code snippet in the document of Fuzz.custom

---

src/Test.elm
src/Test/Internal.elm

Hi, following [suggestions that it would be nicer to have all duplicates at once](https://discourse.elm-lang.org/t/gathering-feedback-on-elm-test-rs-before-1-0-release/6851/6?u=mattpiz), I've come up with a possible implementation of this. Given the following tests:
```elm
concatDup : Test
concatDup =
Test.concat
[ Test.test "should pass" (\_ -> Expect.pass)
, Test.test "should pass" (\_ -> Expect.pass)
, Test.test "should fail" (\_ -> Expect.fail "force failed")
, Test.test "should fail" (\_ -> Expect.fail "force failed")
]
suite : Test
suite =
Test.describe "suite"
[ Test.test "should pass" (\_ -> Expect.pass)
, Test.test "should pass" (\_ -> Expect.pass)
, Test.test "should fail" (\_ -> Expect.fail "force failed")
, Test.test "should fail" (\_ -> Expect.fail "force failed")
] …
```

Aggregate multiple duplicate descriptions at the same level

---

src/Fuzz.elm

This was an oversight: crashing is fine inside REPL but there's nothing stopping people from using it in normal Elm applications. Defaulting to an empty list will be safer.

Stop crashing in Fuzz.examples

---

src/Fuzz.elm

This makes it so that `Fuzz.examples` produces more variety of example, since it can use the first argument as the seed.

Slight improvement to examples

---

src/Test/Fuzz.elm
tests/src/SeedTests.elm

Before this fix elm-test ran the loop `runs-1` times instead of `runs` times. So, eg. 99 times when `{runs = 100}` was specified.
Unfortunately I've had to rewrite all the hardcoded magic constants in the "golden test".

Fix an off-by-one error for {runs = ...} loop

---

README.md

We're talking about "a list of runners" in Test.Runner doc comment, but README only contains `node-test-runner`. It would be fair to mention `elm-test-rs` too.
https://github.com/elm-explorations/test/blob/f4e60c2521157d59053cc3580f6309b3c4b38e83/src/Test/Runner.elm#L8-L11

Mention elm-test-rs when listing test runners

---

src/RandomRun.elm

In elm-in-elm/compiler, in an Expr fuzzer of max depth 3 with lists and strings hardcoded to length 5 this was maxing out.
Now of course the sensible solution was to make the length variable (1-5 etc). but this anecdote means the limit can be reached by more advanced fuzzers.
So let's raise the limit a bit? List of 64k integers still seems OK memory-hungriness-wise.

Increase RandomRun max length from 32k to 64k

---

elm.json
src/Queue.elm
tests/elm.json

This is to prevent issues with testing user code that uses newer versions of `turboMaCk/queue` than the test library has. This is not a problem currently, but it's a potential problem in the future. Let's minimize the number of 3rd party deps we have!
(Thanks to @mpizenberg for making me aware of this)

Vendor the Queue module

---

src/Test/Html/Internal/ElmHtml/ToString.elm

I believe I found an error in the HTML to String code for boolean attributes here:
https://github.com/elm-explorations/test/blob/2bc02f7405622a08215c2acb4303a083d056d0aa/src/Test/Html/Internal/ElmHtml/ToString.elm#L137-L141
In Elm's virtual DOM code, `boolAttribute` is setting a property (not an attribute) of a boolean, true or false: https://github.com/elm/html/blob/94c079007f8a7ed282d5b53f4a49101dd0b6cf99/src/Html/Attributes.elm#L167-L169.
However, rendering these boolean attributes as `key="true"` or `key="false"` is not equivalent to these boolean properties.
For example, take the HTML attribute `hidden`. https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden
Setting `<div hidden>`, `<div hidden="true">`, and `<div hidden="false">` will all result in a hidden div. …

Don't render boolean attributes with a False value to match behavior of HTML property false

---

src/Fuzz.elm
tests/src/FuzzerTests.elm

I needed this function on a project I'm working on so I figured it could be interesting to contribute it back upstream.
edit: By the way, I couldn't run the test locally, I expect to CI to help me about that.

Implement Fuzz.filterMap
